mod critter;
mod fps_counter;
mod genome;
mod heading;
mod instruction;
mod pellet;
mod renderer;
mod stagnation_detector;
mod text;
mod world;

pub use critter::{Critter, MAX_CRITTER_ENERGY};
pub use fps_counter::FpsCounter;
pub use genome::Genome;
pub use heading::Heading;
pub use instruction::Instruction;
pub use pellet::{Pellet, PELLET_COLOR, PELLET_ENERGY, PELLET_RADIUS};
pub use renderer::Renderer;
pub use stagnation_detector::StagnationDetector;
pub use text::pixels as text_pixels;
pub use world::{World, CRITTER_RADIUS};
